spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres

# Credenciais separadas
spring.datasource.username=postgres.sigspoomoxvfsalospbi
spring.datasource.password=amopanqueca

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# (Opcional) ajustar pool para free tier
spring.datasource.hikari.maximum-pool-size=5
